### PR TITLE
Added settings helper class based on dataclass

### PR DESCRIPTION
**Pull request by igo95862**
Type checked, auto-completable and no variant tuples.

Only `ConnectionSettings` implemented so far. Use https://networkmanager.dev/docs/api/latest/nm-settings-dbus.html to add the rest.

Also need helper methods that accept and return new methods.

### CODE REVIEW

**Comment by igo95862** [comment]
What do you think @bernhardkaindl ?

**Comment by bernhardkaindl** [comment]
I think it shows a nice way to export data from a dataclass into variant tuples.

For my use case, also want to retrieve connection settings as object attributes.

It makes my code easier to understand, and I've added an example in #15

**Comment by igo95862** [comment]
> For my use case, also want to retrieve connection settings as object attributes.

The dataclasses also allow that:

```python


def test2() -> None:
    x = NetworkManngerSettings.from_dbus({
        "connection": {
            "id": ("s", 'test'),
            "uuid": ("s", 'test'),
            "type": ("s", "802-11-wireless"),
            "autoconnect": ('b', True),
        }})
    print(x.connection_settings.pretty_id)
```
```
>>> sdbus_async.networkmanager.settings.test2()
test
```

My original commit did not have the `from_dbus` methods but now they do.

**Comment by bernhardkaindl** [comment]
With this, it starts to look very good!

**Comment by bernhardkaindl** [comment]
That's good, and I'd also need to set `connection.ipv4.address_data[0](address = "x.x.x.x", prefix=24)` as well as `connection.ipv4.dns_servers[]`, and so on and (the wifi and modem connection settings).

Would the nested dataclasses for these for be generated or written by hand?

**Comment by igo95862** [comment]
> That's good, and I'd also need to set `connection.ipv4.address_data[0](address = "x.x.x.x", prefix=24)` as well as `connection.ipv4.dns_servers[]`, and so on and (the wifi and modem connection settings).

I am working on adding more.

> Would the nested dataclasses for these for be generated or written by hand?

I am using https://networkmanager.dev/docs/api/latest/nm-settings-dbus.html to write classes by hand. I don't think where is any introspection available for those options.

**Comment by bernhardkaindl** [comment]
I think the dataclasses could be auto-generated from the file `src/libnm-client-impl/nm-settings-docs-gir.xml` which is generated when building network-manager or with the output from `tools/generate-docs-nm-property-infos.py`, specifically `src/libnm-client-impl/nm-property-infos-dbus.xml`, but in my current build of NM it mostly only contains the settings of ipv4 and ipv6, some other interesting domains are empy, in it, but I think that should be fixable.

Finally: *It looks like `src/nmcli/generate-docs-nm-settings-nmcli.xml`, should fit the bill as well even despite it is generated for nmcli.*

Hint: To build the networkmanager source on Debian distros, this should help: `sudo apt-get build-dep network-manager` and `autogen.sh;configure --disable-ovs;make -j4` or `meson . .out;cd .out;ninja -l4`,

**Comment by bernhardkaindl** [comment]
Are you working on it now? I try to hack `tools/generate-docs-nm-settings-docs-merge.py outfile src/nmcli/generate-docs-nm-settings-nmcli.xml` to give a more usable output for generating dataclasses.

**Comment by igo95862** [comment]
I am almost finished with `Ipv4Settings`. Ran in to some issues with `address_data` because it has another vardict inside but I think I have a solution.

**Comment by igo95862** [comment]
Writing the initial class only took about 15 minutes. Fixing the packing and unpacking from dbus is what is taking most time. (plus I had to step away)

**Comment by igo95862** [comment]
I pushed the `Ipv4Settings`. The `address_data` and `route_data` is kind of hacked on. I need a more generic solution.

**Comment by igo95862** [comment]
I added the `WifiSettings` and `WifiSecuritySettings` classes. The vardicts handling should now be generic.

**Comment by bernhardkaindl** [comment]
I've done a lot of work for generating type-classes (currently for this dataclass-driven approach) and have a new branch which I pushed and added a PR for to make it easier to review the changes: #16

There is one remaining hurdle:

Say I want to update a network connection and want to change e.g. the WiFi PSK like so:
```py
    profile.wifi_security.psk = args.password
```
This triggers this mypy error:
```py
error: Item "None" of "Optional[WifiSecuritySettings]" has no attribute "psk"
```

The reason for this that the dataclass-based approach (has to use/uses) Optional[WifiSecuritySettings] to add "802-11-wifi-security" and all the other settings domains which are only present for specific connection types.

My idea for fixing this would be to create specific `ConnectionProfile` top-level classes for each type of connection, and in `.from_dbus()` check what the dict["connection"]["type"] indicates and then get the needed class for that connection_type.

To you see other possible ways to fix this issue?

PS: My Prodict and MetaDict-based approaches does not have this issue.

But it seems, this would be solvable using the different `ConnectionProfile` classes like `ConnectionProfileWireless`, `ConnectionProfileEthernet`, etc. - do you agree that this would be the way forward to fix that?

**Comment by igo95862** [comment]
There is a chance that NetworkManager actually did not return the settings and we will have None in place of it. (for example we asked a wired connection but expected the wireless one)

Here are some solutions:

```
assert profile.wifi_security is not None

if profile.wifi_security is None:
    raise ValueError

if profile.wifi_security is not None:
    do_work()
```
mypy will realize that `profile.wifi_security` would not be None.

**Comment by bernhardkaindl** [comment]
Thanks, that's great! I've pushed an update for #16 to cleanup the naming of the classes.

It should make reviewing the additions easier.

**Comment by igo95862** [comment]
@bernhardkaindl big big thank you for working on the branch.

I am not yet ready to squash and merge. I will do couple of reviews and experiments and then merge.

**Comment by igo95862** [comment]
> @igo95862 Merge this weekend?
> 
> If needed, I could add some more updates to examples and possibly test cases.

Yes, I think so.

**Pull request merged**
