### PR TITLE
Add class ConnectionType

### PR DESCRIPTION
**Pull request by bernhardkaindl**
Add enums.ConnectionType (on top of #24)

### CODE REVIEW

**Comment by bernhardkaindl** [comment]
@igo95862 
I took the example for constructing the enum of stackoverflow because you wrote that you planned to do that using `typing.Literal`:
```py
class ConnectionType(Enum):
    ADSL: Literal["adsl"] = "adsl"
    BLUETOOTH: Literal["bluetooth"] = "bluetooth"
    BOND: Literal["bond"] = "bond"
    BRIDGE: Literal["bridge"] = "bridge"
    ...
``` 
Compared to the simple variant that I generated before, one needs to get the `str` of the Literal before comaring it with a string:
```
        if profile.connection.connection_type == str(ConnectionType.WIRELESS):
            assert profile.wireless
```
I guess this would need a second commit to use ConnectionType for connection.connection_type as well, but for now I'm just putting this out for review to see if this was the planned use of typing.Literal.

This was the simple variant I used before:
```
class ConnectionType:
    SIXLOWPAN = "6lowpan"
    ADSL = "adsl"
    BLUETOOTH = "bluetooth"
    BOND = "bond"
    BRIDGE = "bridge"
```

**Comment by igo95862** [comment]
Hmm on a second thought..........

Is mypy going to complain about this? Will python-sdbus be able to encode it?
```
profile.connection.connection_type = ConnectionType.WIRELESS
```

Also stackoverflow gives me another example of StrEnum: https://stackoverflow.com/questions/58608361/string-based-enum-in-python/58608362#58608362

**Comment by bernhardkaindl** [comment]
> Hmm on a second thought..........
> 
> Is mypy going to complain about this? Will python-sdbus be able to encode it?
> 
> ```
> profile.connection.connection_type = ConnectionType.WIRELESS
> ```

Good catch! It won't work this way with an Enum! (see below)
> Also stackoverflow gives me another example of StrEnum: https://stackoverflow.com/questions/58608361/string-based-enum-in-python/58608362#58608362

I've researched this as well and tried these.

Finally, I understood that Enum means that one has to use `.value`:  :-1: 
```py
profile.connection.connection_type = ConnectionType.WIRELESS.value
```
Instead, I really want the simple use:
```py
profile.connection.connection_type = ConnectionType.WIFI
```

To support this (which is my sole reason for proposing this class), I reverted this PR to the simple class I used successfully:
```py
class ConnectionType:
    ...
    WIFI = "802-11-wireless"
    WPAN = "wpan"
```
BTW, I renamed `.WIRELESS` to `WIFI` now because in `.enums.DeviceType`, `WIFI` is used as well and I need to derive the `ConnectionType` from the `DeviceType` string at runtime (#26).

The new commit makes use of `ConnectionType.WIFI` in [examples/async/add-wifi-psk-connection-async.py](https://github.com/python-sdbus/python-sdbus-networkmanager/pull/25/files#diff-d6f844d7cbb63bae163a46258f7a92186730700da0c2996e10e740b5e927d5a2):
```py
     profile = ConnectionProfile(
         connection=ConnectionSettings(
             uuid=str(uuid.uuid4()),
-            connection_type='802-11-wireless',
+            connection_type=ConnectionType.WIFI,
             connection_id=args.conn_id,
             autoconnect=args.auto,
         ),
```
This is working correctly and is checked with `mypy --strict`

**Comment by igo95862** [comment]
Ok. I cherry picked cae9fbd3946bad3ad91d68b994f06746faa38a5b .

**Pull request closed without merging**
